site_name: Simba

theme:
 name: material
 palette:
   scheme: default

#Extensions
markdown_extensions:
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - tables
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages
  - roamlinks
  - glightbox

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js